### ISSUE TITLE
Can't start training

### ISSUE THREAD

**Issue by EasonLin536** [ChristophReich1996/DeepFoveaPP_for_Video_Reconstruction_and_Super_Resolution#2]
Hi, @ChristophReich1996, I can't start the training process.
After I execute `python main.py --train`, I got this
```
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    model_wrapper.train(epochs=20)
  File "/home/eason/research/DeepFovea++/model_wrapper.py", line 207, in train
    self.discriminator_network(label),
  File "/home/anaconda3/envs/deepfovea++/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/deepfovea++/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/deepfovea++/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/eason/research/DeepFovea++/discriminator.py", line 45, in forward
    output = output.view(1, self.in_channels * 2, self.frames, output.shape[2], output.shape[3])
RuntimeError: shape '[1, 6, 6, 192, 256]' is invalid for input of size 3538944
```
I checked the prediction of the generator and the label and both of their dimension is `[2, 18, 768, 1024]`
I'm not sure if there's anything missing. 
(By the way, I successfully executed validation.)

Thanks.

**Comment by EasonLin536** [comment]
After I change the batch_size and n_gpu to 1, the error:
```
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    model_wrapper.train(epochs=20)
  File "/home/eason/research/DeepFovea++/model_wrapper.py", line 234, in train
    flow = self.pwc_net(prediction_pair)
  File "/home/anaconda3/envs/deepfovea++/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/deepfovea++/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/deepfovea++/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/eason/research/DeepFovea++/pwc_net.py", line 192, in forward
    corr6 = self.corr(c16, c26)
  File "/home/anaconda3/envs/deepfovea++/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/eason/research/DeepFovea++/correlation/correlation.py", line 66, in forward
    self.corr_multiply)(input1, input2)
  File "/home/anaconda3/envs/deepfovea++/lib/python3.7/site-packages/torch/autograd/function.py", line 160, in __call__
    "Legacy autograd function with non-static forward method is deprecated. "
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
```
Did you encounter this problem? Thanks

**Comment by EasonLin536** [comment]
Hi, @ChristophReich1996, I finally start the training process successfully.
However, I can't run multiple batches on 1 gpu (32G).
It seems that your code only supports batch_size = n_gpu training.
Is it possible to run multiple batches on 1 gpu in your code?
Thanks.
